### ISSUE TITLE
extend_from_slice() + into_vec() produce inconsistent results

### ISSUE THREAD

**Issue by inikulin** [myrrlyn/bitvec#65] opened 2020-06-29 19:23 UTC
I've noticed some flakiness in my test that use bitvec and it turns out that combination of these two functions produce inconsistent results. 

To reproduce run the following test
```rust
#[test]
fn oops() {
     let mut v = BitVec::<Msb0, u8>::default();

     v.extend_from_slice(&bitvec![Msb0, u8; 0, 1]);

     assert_eq!(v.into_vec(), [0b0100_0000]);
}
```

in loop using :
```sh
while cargo test oops; do :; done
```
(running using in-code loop doesn't have the same effect for some reason)

The test usually fails for me within a minute of running the command.

**Comment by sharksforarms** [comment] 2020-06-29 20:21
Possibly related: https://github.com/myrrlyn/bitvec/issues/62

**Comment by myrrlyn** [comment] 2020-07-05 19:56
This does not replicate in my development branch locally, so I assume that it will not be present in the `0.18` release. I will update this issue when I manage to actually release it.

**Comment by myrrlyn** [comment] 2020-08-06 17:14
Can you test current `develop` and let me know if the issue persists? Thank you for the report!

**Comment by myrrlyn** [comment] 2020-08-06 19:37
Turns out the problem is uninitialized memory brought into the buffer through `.extend_from_bitslice`. My closing comment in #62 describes why this occurs in more detail. It is fixed on currently `develop`, and will be in the forthcoming `0.18` release. Thank you for your patience.

**Closed by myrrlyn** 2020-08-06 19:37 UTC
